### ISSUE TITLE
Cursor Settings extension has no effect in Codium (OK in Code)

### ISSUE THREAD

**Issue by sjsepan3** [drbap/cursor-settings-for-vscode#1]
Type: <b>Bug</b>

Cursor Settings extension installs, and menu appears in status bar, but it does not customize cursor in VSCodium, although it does work in VSCode.
https://marketplace.visualstudio.com/items?itemName=BernardoPires.cursor-settings
Ran Extension Bisect and it pointed to the extension at the end.

VSCodium:
Version: 1.89.1
Release: 24130
Commit: a045dcfceda27f896936bfd8cbf524f6a93a2f46
Date: 2024-05-09T18:30:40.866Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.0-107-generic

VSCode:
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.0-107-generic

System:
System:
  Kernel: 5.15.0-107-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Dell product: OptiPlex 5040 v: N/A serial: <superuser required> Chassis:
    type: 3 serial: <superuser required>
  Mobo: Dell model: 0R790T v: A00 serial: <superuser required> UEFI-[Legacy]: Dell v: 1.2.7
    date: 01/15/2016
Battery:
  Device-1: hidpp_battery_0 model: Logitech M570 serial: <filter> charge: 20% rechargeable: yes
    status: Discharging
CPU:
  Info: quad core model: Intel Core i5-6500 bits: 64 type: MCP smt: <unsupported> arch: Skylake-S
    rev: 3 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 2923 high: 2973 min/max: 800/3600 cores: 1: 2845 2: 2973 3: 2964 4: 2913
    bogomips: 25599
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 535.171.04 pcie: speed: 8 GT/s
    lanes: 4 ports: active: none off: HDMI-A-1 empty: DVI-D-1 bus-ID: 01:00.0 chip-ID: 10de:1d01
    class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x2160 s-dpi: 162 s-size: 602x341mm (23.7x13.4") s-diag: 692mm (27.2")
  Monitor-1: HDMI-0 res: 3840x2160 hz: 60 dpi: 163 size: 600x340mm (23.6x13.4")
    diag: 690mm (27.2")
  OpenGL: renderer: NVIDIA GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 535.171.04
    direct render: Yes
Audio:
  Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3 chip-ID: 8086:a170 class-ID: 0403
  Device-2: NVIDIA GP108 High Definition Audio driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 4 bus-ID: 01:00.1 chip-ID: 10de:0fb8 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-107-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I219-V vendor: Dell driver: e1000e v: kernel port: N/A bus-ID: 00:1f.6
    chip-ID: 8086:15b8 class-ID: 0200
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: vboxnet0 state: down mac: <filter>
Drives:
  Local Storage: total: 2.05 TiB used: 2.03 TiB (99.1%)
  ID-1: /dev/sda vendor: SanDisk model: SD8SBAT-256G-1006 size: 238.47 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: 1006 scheme: GPT
  ID-2: /dev/sdb vendor: Western Digital model: WDS100T2B0A-00SM50 size: 931.51 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: 20WD scheme: MBR
  ID-3: /dev/sdd type: USB vendor: Western Digital model: WD My Passport 25E1 size: 931.48 GiB
    type: N/A serial: <filter> rev: 1021 scheme: GPT
Partition:
  ID-1: / size: 233.62 GiB used: 71.51 GiB (30.6%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 47.2 MiB used: 6 MiB (12.8%) fs: vfat dev: /dev/sda2
  ID-3: /home size: 915.82 GiB used: 761.86 GiB (83.2%) fs: ext4 dev: /dev/sdb1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 512 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 16 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-3:2 info: 816820090226 type: Mass Storage driver: usb-storage interfaces: 1
    rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 3207:0300 class-ID: 0806 serial: <filter>
  Device-2: 1-5:3 info: Logitech Unifying Receiver type: Keyboard,Mouse,HID
    driver: logitech-djreceiver,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s power: 98mA
    chip-ID: 046d:c52b class-ID: 0300
  Device-3: 1-9:4 info: Western Digital My Passport (WD20NMVW) type: Mass Storage
    driver: usb-storage interfaces: 1 rev: 2.1 speed: 480 Mb/s power: 500mA chip-ID: 1058:25e1
    class-ID: 0806 serial: <filter>
  Hub-2: 2-0:1 info: Super-speed hub ports: 10 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 29.8 C pch: 58.0 C mobo: 27.8 C gpu: nvidia temp: 37 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 86%
Repos:
  Packages: note: see --pkg apt: 3777
  Active apt repos in: /etc/apt/sources.list
    1: deb [trusted=yes] http: //www.raqsoft.com/raqesproc/update/debian/ /
  Active apt repos in: /etc/apt/sources.list.d/gambas-team-gambas3-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/gambas-team-gambas3-jammy.gpg] https: //ppa.launchpadcontent.net/gambas-team/gambas3/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/jonaski-strawberry-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/jonaski-strawberry-jammy.gpg] https: //ppa.launchpadcontent.net/jonaski/strawberry/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/krupkat-code-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/krupkat-code-jammy.gpg] https: //ppa.launchpadcontent.net/krupkat/code/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vivaldi.list
    1: deb [arch=amd64] https: //repo.vivaldi.com/stable/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
  Active apt repos in: /etc/apt/sources.list.d/vscodium.list
    1: deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https: //download.vscodium.com/debs vscodium main
  Active apt repos in: /etc/apt/sources.list.d/warpdotdev.list
    1: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/warpdotdev.gpg] https: //releases.warp.dev/linux/deb stable main
Info:
  Processes: 295 Uptime: 5h 49m wakeups: 12 Memory: 15.54 GiB used: 5 GiB (32.2%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 clang: 14.0.0-1ubuntu1.1
  Client: Unknown python client inxi: 3.3.13

Extension version: 1.0.0
VSCodium version: VSCodium 1.89.1 (a045dcfceda27f896936bfd8cbf524f6a93a2f46, 2024-05-09T18:30:40.866Z)
OS version: Linux x64 5.15.0-107-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.54GB (10.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sjsepan3** [comment]
For good measure, I disabled all extensions, and re-enabled Cursor Settings, and even re-started the app, but same behavior in VSCodium.

**Comment by sjsepan3** [comment]
For further experimentation, I installed it in Azure Data Studio, and it does work there. So far it is just in VSCodium that it does not work.

ADS:
Version: 1.48.0
Commit: 4970733324ef8254b7c22a5dc55af7f8a1dea93f
Date: 2024-02-26T20:54:08.538Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-107-generic

**Comment by sjsepan3** [comment]
I found a case where the extension DOES work on VSCodium: on my laptop...

VSCodium:
Version: 1.89.1
Release: 24130
Commit: a045dcfceda27f896936bfd8cbf524f6a93a2f46
Date: 2024-05-09T18:30:40.866Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.0-107-generic

VSCode:
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.0-107-generic

System:
System:
  Kernel: 5.15.0-107-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: TOSHIBA product: Satellite P775 v: PSBY1U-08003L
    serial: <superuser required> Chassis: type: 10 serial: <superuser required>
  Mobo: TOSHIBA model: PHRAA v: 1.00 serial: <superuser required> BIOS: TOSHIBA v: 2.10
    date: 09/06/2012
Battery:
  ID-1: BAT1 charge: 42.5 Wh (100.0%) condition: 42.5/48.6 Wh (87.4%) volts: 12.4 min: 10.8
    model: COMPAL PABAS0241231 type: Li-ion serial: <filter> status: N/A
CPU:
  Info: dual core model: Intel Core i5-2450M bits: 64 type: MT MCP smt: enabled arch: Sandy Bridge
    rev: 7 cache: L1: 128 KiB L2: 512 KiB L3: 3 MiB
  Speed (MHz): avg: 2455 high: 2705 min/max: 800/3100 cores: 1: 2237 2: 2395 3: 2483 4: 2705
    bogomips: 19956
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Toshiba
    driver: i915 v: kernel ports: active: LVDS-1 empty: DP-1,HDMI-A-1,VGA-1 bus-ID: 00:02.0
    chip-ID: 8086:0126 class-ID: 0300
  Device-2: Alcor Micro USB 2.0 Camera type: USB driver: uvcvideo bus-ID: 1-1.4:4
    chip-ID: 058f:b003 class-ID: 0e02 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1600x900 s-dpi: 96 s-size: 423x238mm (16.7x9.4") s-diag: 485mm (19.1")
  Monitor-1: LVDS-1 model: AU Optronics res: 1600x900 hz: 60 dpi: 106
    size: 382x214mm (15.0x8.4") diag: 438mm (17.2") modes: 1600x900
  OpenGL: renderer: Mesa Intel HD Graphics 3000 (SNB GT2) v: 3.3 Mesa 23.2.1-1ubuntu3.1~22.04.2
    direct render: Yes
Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: Toshiba
    driver: snd_hda_intel v: kernel bus-ID: 00:1b.0 chip-ID: 8086:1c20 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-107-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Toshiba driver: r8169
    v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: e000 bus-ID: 02:00.0 chip-ID: 10ec:8168
    class-ID: 0200
  IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel Centrino Wireless-N + WiMAX 6150 driver: iwlwifi v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 bus-ID: 03:00.0 chip-ID: 8086:0885 class-ID: 0280
  IF: wlp3s0 state: down mac: <filter>
  Device-3: Intel Intel Centrino Wireless-N + WiMAX 6150 type: USB driver: N/A bus-ID: 1-1.2:3
    chip-ID: 8087:07d6 class-ID: 0000
Drives:
  Local Storage: total: 232.89 GiB used: 76.63 GiB (32.9%)
  ID-1: /dev/sda vendor: Samsung model: SSD 840 EVO 250GB size: 232.89 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: CB6Q scheme: MBR
Partition:
  ID-1: / size: 222.05 GiB used: 76.63 GiB (34.5%) fs: ext4 dev: /dev/sda6
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 136.1 MiB (6.6%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Full speed or root hub ports: 2 rev: 2.0 speed: 480 Mb/s chip-ID: 1d6b:0002
    class-ID: 0900
  Hub-2: 1-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 speed: 480 Mb/s
    chip-ID: 8087:0024 class-ID: 0900
  Device-1: 1-1.2:3 info: Intel Intel Centrino Wireless-N + WiMAX 6150 type: WiFi driver: N/A
    interfaces: 1 rev: 2.0 speed: 480 Mb/s chip-ID: 8087:07d6 class-ID: 0000
  Device-2: 1-1.4:4 info: Alcor Micro USB 2.0 Camera type: Video driver: uvcvideo interfaces: 2
    rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 058f:b003 class-ID: 0e02 serial: <filter>
  Hub-3: 2-0:1 info: Full speed or root hub ports: 2 rev: 2.0 speed: 480 Mb/s chip-ID: 1d6b:0002
    class-ID: 0900
  Hub-4: 2-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 speed: 480 Mb/s
    chip-ID: 8087:0024 class-ID: 0900
  Hub-5: 3-0:1 info: Hi-speed hub with single TT ports: 2 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-6: 4-0:1 info: Super-speed hub ports: 2 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 64.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: apt: 2696
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/cappelikan-ppa-jammy.list
    1: deb http: //ppa.launchpad.net/cappelikan/ppa/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/gambas-team-gambas3-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/gambas-team-gambas3-jammy.gpg] https: //ppa.launchpadcontent.net/gambas-team/gambas3/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/jonaski-strawberry-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/jonaski-strawberry-jammy.gpg] https: //ppa.launchpadcontent.net/jonaski/strawberry/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/krupkat-code-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/krupkat-code-jammy.gpg] https: //ppa.launchpadcontent.net/krupkat/code/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64] https: //packages.microsoft.com/repos/vscode stable main
  Active apt repos in: /etc/apt/sources.list.d/vscodium.list
    1: deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https: //download.vscodium.com/debs vscodium main
Info:
  Processes: 268 Uptime: 1d 2h 43m wakeups: 2 Memory: 5.69 GiB used: 3.2 GiB (56.2%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Unknown python client inxi: 3.3.13

**Comment by sjsepan3** [comment]
On that same laptop, the extension DOES NOT work with the version of ADS that was installed...

Version: 1.45.0
Commit: 8eff468100f02157f2219335f7a566d14451ca49
Date: 2023-07-24T18:11:05.791Z
VS Code: 1.79.0
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-107-generic

...but even when upgraded to the version that was on the desktop, it still DOES NOT...

Version: 1.48.0
Commit: 4970733324ef8254b7c22a5dc55af7f8a1dea93f
Date: 2024-02-26T20:54:08.538Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-107-generic

...so in summary VSCodium works on the 2nd machine (laptop) but not the first (desktop), Azure Data Studio works on the desktop, but not on the laptop.

**Comment by drbap** [comment]
Hi @sjsepan3,

First of all, thank you very much for stopping by, testing the extension and the detailed information provided on the issue on Codium.

I made this extension to work primarily in Visual Studio Code. I use the cursor settings extension without any problems in VS Code. So I decided to share it with other people, because I use it every day (it's useful for me). I like to use one type of cursor for writing, another for coding, and so on... I also like to change the blinking (mainly between solid and blinking cursor).

The purpose of this extension is to quickly change the cursor appearance without using the Settings tab or settings.json (using the status bar and command palette).

Regarding Codium, I will have to check this issue in more detail. I'll try to fix it, but remember it was made for VS Code, I hope it's working well for you in Code.

All the best

**Comment by drbap** [comment]
Please select "**Add folder to workspace**" and try again. It is working well for me in Codium 1.89 too.

**Comment by drbap** [comment]
I used the option to alter just the cursor settings in the current workspace. I can make it global.

**Comment by sjsepan3** [comment]
Thank You for your quick reply. :-)

I wasn't aware that the cursor could be changed with the settings.json. I will look into that. UPDATE: OK, I see them in settings!

I split my time between VSCode and VSCodium. So far it IS working in VSCode in every instance!

I mentioned Azure Data Studio only for completeness and comparison, as it springs from the Code-OSS codebase too -- but its not really critical. I tested my own color themes against all three because of that, though ... so I thought I'd see what this extension did, in the hope of finding some factor that pointed to an answer.

**Comment by sjsepan3** [comment]
> Please select "**Add folder to workspace**" and try again. It is working well for me in Codium 1.89 too.

Yup, that was it, alright! In every case it was the presence/absence of a workspace.

**Comment by sjsepan3** [comment]
> I used the option to alter just the cursor settings in the current workspace. I can make it global.

I can see that being useful, or maybe an option. It would allow the behavior for a single file with no workspace, although I can see the utility of possibly having a different cursor for different types of files/projects.

**Comment by drbap** [comment]
I will upload a new version of the extension later today, which should work well regardless of the workspace folder. Thanks again for letting me know.

**Comment by sjsepan3** [comment]
> I will upload a new version of the extension later today, which should work well regardless of the workspace folder. Thanks again for letting me know.

Thank You for looking into this, and the info! :-)

**Comment by drbap** [comment]
Please keep the issue open till I upload the newer version. It should be ready and uploaded in a few hours (can't recompile it now).

All the best

**Comment by drbap** [comment]
Please check **Cursor Settings verson 1.0.1**. Let me know if it is working well for you (Code and Codium).

All the best and thanks again for testing it.

**Comment by sjsepan3** [comment]
> Please check **Cursor Settings verson 1.0.1**. Let me know if it is working well for you (Code and Codium).
> 
> All the best and thanks again for testing it.

Yes! That is working; Thank You. You can close this.
Cheers

**Comment by drbap** [comment]
Thank you. Cheers, my friend.
